<a href="https://colab.research.google.com/github/TurinShayla/Deep-Learning/blob/main/CodingANNPractise.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Artificial Neural Network

###Importing the libraries

In [ ]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import tensorflow as tf

In [ ]:
tf.__version__

'2.7.0'

## Part 1 Data Preprocessing



###Importing the dataset

In [ ]:
dataset=pd.read_csv('Churn_Modelling.csv')
X=dataset.iloc[:,3:-1].values # first 3 ta column dorkar nai, tai all column prothom tin ta bad diye shuru ebong shesher ag porjnto
Y=dataset.iloc[:,-1].values
print(X)
print(Y)

Check missing data

In [ ]:
dataset.isnull().values.any()
dataset.isnull().sum()

RowNumber          0
CustomerId         0
Surname            0
CreditScore        0
Geography          0
Gender             0
Age                0
Tenure             0
Balance            0
NumOfProducts      0
HasCrCard          0
IsActiveMember     0
EstimatedSalary    0
Exited             0
dtype: int64

###Encoding categorical data

Label Encoding the "Gender" column

In [ ]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
X[:,2]=le.fit_transform(X[:,2])

One Hot Encoding the "Geography" column

In [ ]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [1])], remainder='passthrough')
X = np.array(ct.fit_transform(X))

In [ ]:
print(X)

[[1.0 0.0 0.0 ... 1 1 101348.88]
 [0.0 0.0 1.0 ... 0 1 112542.58]
 [1.0 0.0 0.0 ... 1 0 113931.57]
 ...
 [1.0 0.0 0.0 ... 0 1 42085.58]
 [0.0 1.0 0.0 ... 1 0 92888.52]
 [1.0 0.0 0.0 ... 1 0 38190.78]]


##Split training and test set

In [ ]:
from sklearn.model_selection import train_test_split
X_train,X_test,Y_train, Y_test=train_test_split(X,Y,test_size=0.2,random_state=0)

### Feature Scaling
Fundamental steps
StandardScaler performs the task of Standardization. Usually a dataset contains variables that are different in scale. For e.g. an Employee dataset will contain AGE column with values on scale 20-70 and SALARY column with values on scale 10000-80000.

In [ ]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
X_train=sc.fit_transform(X_train)
X_test=sc.fit_transform(X_test)

## Part 2 - Building the ANN

### Initializing the ANN

In [ ]:
ann=tf.keras.models.Sequential()

### Adding the input layer and the first hidden layer

In [ ]:
ann.add(tf.keras.layers.Dense(units=6,activation='relu'))

### Adding the second hidden layer

In [ ]:
ann.add(tf.keras.layers.Dense(units=6,activation='relu'))

### Adding the output layer

In [ ]:
ann.add(tf.keras.layers.Dense(units=1,activation='sigmoid'))

#Part 3- Training the ANN

### Compiling the ANN

In [ ]:
ann.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])

### Training the ANN on the Training set

In [ ]:
ann.fit(X_train, Y_train, batch_size = 32, epochs = 100)

Epoch 1/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3736 - accuracy: 0.8445
Epoch 2/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3698 - accuracy: 0.8453
Epoch 3/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3662 - accuracy: 0.8482
Epoch 4/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3616 - accuracy: 0.8525
Epoch 5/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3567 - accuracy: 0.8568
Epoch 6/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3531 - accuracy: 0.8553
Epoch 7/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3508 - accuracy: 0.8600
Epoch 8/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3481 - accuracy: 0.8591
Epoch 9/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3453 - accuracy: 0.8596
Epoch 10/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3435 - accura

## Part 4 - Making the predictions and evaluating the model

### Predicting the result of a single observation

### Predicting the Test set results

In [ ]:
y_pred = ann.predict(X_test)
y_pred = (y_pred > 0.5)
print(np.concatenate((y_pred.reshape(len(y_pred),1), Y_test.reshape(len(Y_test),1)),1))

[[0 0]
 [0 1]
 [0 0]
 ...
 [0 0]
 [0 0]
 [0 0]]


### Making the Confusion Matrix

In [ ]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(Y_test, y_pred)
print(cm)
accuracy_score(Y_test, y_pred)

[[1519   76]
 [ 206  199]]


0.859